services:
  postgres:
    image: postgres:16
    container_name: urban-postgres
    environment:
      POSTGRES_DB: urban_db
      POSTGRES_USER: urban_user
      POSTGRES_PASSWORD: urban_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: khversatile/urban-waste-manager:1.0.0
    env_file:
      - .env
    ports:
      - "8083:8083"
    depends_on:
      - postgres

volumes:
  postgres_data:
