spring.application.name=UrbanWasteManager
server.port=${PORT}
spring.config.import=optional:file:./.env[.properties]

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.autoconfigure.exclude=org.springframework.ai.model.openai.autoconfigure.OpenAiAudioSpeechAutoConfiguration,org.springframework.ai.vectorstore.s3.autoconfigure.S3VectorStoreAutoConfiguration

app.default-admin.email=admin@urbanwaste.com
app.default-admin.password=admin123